
bootstrap.servers=xyz:9092
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="abc" password="def";

monitor.canary.produce.enabled=true
monitor.canary.produce.topics=canary
monitor.canary.consume.enabled=true
monitor.canary.consume.topics=canary

monitor.canary.messages.per.partition.per.second=2.0
